name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name : Setup build and test project
      run: |
        source ./cmds/build-env.sh
        ./cmds/test.sh
        ./cmds/build.sh


